### ISSUE TITLE
ValueError: Error when checking target: expected dense_2 to have 2 dimensions, but got array with shape (512430, 1, 1971)Replication File 2 of 3  

### ISSUE THREAD

**Issue by deepakkuk** [benradford/replication_arxiv_1805_03735#1]
Dear benradford,
thanks for this repository. since facing issue of shape Replication File 2 of 3 
 File "asa_sdss_replication_models.py", line 167, in <module>
    model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size, validation_split=validation_split, class_weight = 'auto')
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1555, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1413, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 142, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected dense_2 to have 2 dimensions, but got array with shape (512430, 1, 1971)

**Comment by benradford** [comment]
I will look into this. Can you tell me:

1. what data are you pointing the scripts to?
2. did you make any changes to File 1 or 2?
3. are you using Tensorflow or Theano as the backend?
4. What version of Python and Keras are you using?

Thank you!

**Comment by deepakkuk** [comment]
1. I used cicids 2017 dataset https://www.unb.ca/cic/datasets/ids-2017.html
2. In file one i got this error AttributeError: 'dict' object has no attribute 'iteritems'
that i resolve using : use dict.items(), dict.keys(), and dict.values() respectively. According to this link https://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems
3.i m using same code probably tensorflow it give warning keep_dim
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py:1238: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py:1340: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
4.python version 3.5.2 and keras version 2.0.9

**Comment by benradford** [comment]
Can you replicate this in Python 2.7? I originally wrote this code for 2.7 and that is why you got errors in iteritems(). I should have made that clear in the documentation. I will update the README file to specify version numbers for dependencies soon. I am sorry for the confusion!

**Comment by benradford** [comment]
If you're using Anaconda (which I recommend) it should be very easy to install a Py 2.7 kernel alongside 3.5: [https://docs.anaconda.com/anaconda/user-guide/tasks/switch-environment/](https://docs.anaconda.com/anaconda/user-guide/tasks/switch-environment/ )

**Comment by benradford** [comment]
@deepakkuk did that solve the problem?

**Comment by deepakkuk** [comment]
> @deepakkuk did that solve the problem?
sry for delay in response, due to resource unavailability it take time.
using python 2.7 Replication File 2 of 3 issue mention above resolved.

**Comment by deepakkuk** [comment]
> If you're using Anaconda (which I recommend) it should be very easy to install a Py 2.7 kernel alongside 3.5: https://docs.anaconda.com/anaconda/user-guide/tasks/switch-environment/

Since best of my knowledge NVIDIA can't provide docker for Anaconda so using dgx i can't able to try this solution is it possible to implement same using python3 without using python 2 version?

**Comment by benradford** [comment]
https://stackoverflow.com/questions/28218466/unpickling-a-python-2-object-with-python-3

That's because you're trying to open py2 pickles in py3. Check that link for more info.
