### ISSUE TITLE
Only 13 classes are present in the data but in code you have taken 1971.

### ISSUE THREAD

**Issue by deepakkuk** [benradford/replication_arxiv_1805_03735#3]
Dear sir,

I was trying to understand the code along with the CICIDS2017 dataset. I found that total classes present in the dataset is 13 while in your last dense layer you have used 1971 classes. I am little confused. Please tell me how you got 1971 classes. I will be very thankful to you.

![Screenshot from 2019-05-08 12-18-22](https://user-images.githubusercontent.com/33250220/57355340-6b885380-718b-11e9-83b0-1aca2d460ee6.png)

**Comment by benradford** [comment]
This is expected behavior. The model does not predict attack classes; it predicts the future sequence token (of which there are 1971). Attacks are estimated using the error terms of these predictions.

**Comment by deepakkuk** [comment]
> This is expected behavior. The model does not predict attack classes; it predicts the future sequence token (of which there are 1971). Attacks are estimated using the error terms of these predictions.

thank you sir
